id: P006721
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG8527
  title: བསྟན་འགྱུར་གསོ་རིག་གཅེས་བཏུས།
  author: ''
  volumes:
    69b6c78c22404902ba6a21ba4cde817a:
      image_group_id: I1KG8559
      title: ''
      volume_number: 1
      total_pages: 382
