id: P006721
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 12:19:10.512609
source_metadata:
  id: bdr:W1KG8527
  title: བསྟན་འགྱུར་གསོ་རིག་གཅེས་བཏུས།
  author: ''
  volumes:
    69b6c78c22404902ba6a21ba4cde817a:
      image_group_id: I1KG8559
      title: ''
      volume_number: 1
      total_pages: 382
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
